// Silly baby-shower themed drawing prompts. Kept PG and group-friendly.
module.exports = [
  'projectile spit-up',
  'diaper blowout',
  '3am zombie feeding',
  'onesie with 100 snaps',
  'baby monitor paranoia',
  'toddler tantrum in the cereal aisle',
  'dad falling asleep standing up',
  'baby food face plant',
  'grandma smothering the baby in kisses',
  'stroller that will not fold',
  'colic screaming contest',
  'baby shower mimosa tower',
  'nursery Pinterest fail',
  'labor day playlist',
  'hospital bag packed three months early',
  'baby proofing gone wrong',
  'unsolicited parenting advice',
  'swaddle burrito',
  'teething ring chew toy',
  'baby first bath panic',
  'spilled breast milk tragedy',
  'car seat instruction maze',
  'diaper genie overflow',
  'baby shark on repeat forever',
  'nap schedule spreadsheet',
  'postpartum belly selfie',
  'avocado baby food mess',
  'cloth versus disposable diaper debate',
  'sleep training bootcamp',
  'baby first haircut meltdown',
  'gender reveal explosion',
  'onesie says dad needs coffee',
  'five second rule pacifier',
  'baby led weaning chaos',
  'cluster feeding marathon',
  'matching family pajama photoshoot',
  'diaper bag the size of a suitcase',
  'baby first snow outfit overkill',
  'burp cloth collection',
  'white noise machine addiction',
  'toddler refusing the car seat',
  'spit-up on every shoulder',
  'baby monitor catching dad singing',
  'first steps face plant',
  'grandparents fighting over holding rights',
  'baby sock disappearing in the dryer',
  '3am google search spiral',
  'toddler yogurt hair salon',
  'baby shower game gone too competitive',
  'dad changing his first diaper',
  'mom brain losing the car keys',
  'baby first Halloween costume',
  'fourth outfit change before noon',
  'sleep regression despair',
  'pregnancy craving pickles and ice cream',
  'baby registry gone overboard',
  'stroller traffic jam at the mall',
  'toddler negotiating bedtime like a lawyer',
  'baby first food fight',
  'postpartum hormone rollercoaster',
  'diaper explosion mid-change',
  'baby burping on grandpa',
  'sleep-deprived parents at Target at 2am',
  'baby wearing a onesie backwards all day',
  'toddler stealing the dog food',
  'the world biggest baby yawn',
  'circle of relatives passing the baby around',
  'baby refusing every bottle except one',
  'dad practicing swaddling on a teddy bear',
];
